dist: trusty

language: python
python:
    - "2.7"
addons:
    postgresql: '9.6'
env:
    - CKANVERSION=2.8
install:
    - bash bin/travis-build.bash
services:
    - postgresql
    - redis
script: sh bin/travis-run.sh
after_success: coveralls
sudo: required
cache:
  directories:
    - $HOME/.cache/pip
