name: Run tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: openknowledge/ckan-dev:2.9

    services:
      solr:
        image: ckan/ckan-solr-dev:2.9

      postgres:
        image: ckan/ckan-postgres-dev:2.9
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      CKAN_SQLALCHEMY_URL: postgresql://postgres:pass@postgres/ckan_test
      CKAN_DATASTORE_WRITE_URL: postgresql://datastore_write:pass@postgres/datastore_test
      CKAN_DATASTORE_READ_URL: postgresql://datastore_read:pass@postgres/datastore_test
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Apply CKAN core patches
        run: ./bin/apply-patches.bash

      - name: Install CKAN extensions required under test
        run: ./bin/install-extensions.bash

      - name: Install ckanext-unhcr plugin
        run: |
          python3 setup.py develop
          pip install --upgrade -r requirements.txt
          pip install --upgrade -r dev-requirements.txt

      - name: Initialize DB
        run: ./bin/init-db.bash

      - name: Ensure assets are up-to-date
        run: |
          apk add --update npm
          npm ci
          make assets
          git diff --exit-code ./ckanext/unhcr/fanstatic

      - name: Ensure deposited_dataset schema is up-to-date
        run: |
          python3 scripts/generate_deposited_dataset_schema.py
          git diff --exit-code ./ckanext/unhcr/schemas

      - name: Run tests
        run: |
          pytest \
            --ckan-ini=test.ini \
            --cov=ckanext.unhcr \
            --cov-report=xml \
            --cov-append \
            --disable-warnings \
            ckanext/unhcr/tests/pt

      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
