name: Run tests
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        ckan-version: ['2.9-py2', '2.9']
      fail-fast: false

    name: CKAN ${{ matrix.ckan-version }}
    runs-on: ubuntu-latest

    container:
      image: openknowledge/ckan-dev:${{ matrix.ckan-version }}

    services:
      solr:
        image: ckan/ckan-solr-dev:${{ matrix.ckan-version }}

      postgres:
        image: ckan/ckan-postgres-dev:${{ matrix.ckan-version }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@postgres/ckan_test
      CKAN_DATASTORE_WRITE_URL: postgresql://datastore_write:pass@postgres/datastore_test
      CKAN_DATASTORE_READ_URL: postgresql://datastore_read:pass@postgres/datastore_test
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Apply CKAN core patches
        run: ./bin/apply-patches.bash

      - name: Install CKAN extensions required under test
        run: ./bin/install-extensions-${{ matrix.ckan-version }}.bash

      - name: Install ckanext-unhcr plugin
        run: ./bin/install-unhcr-${{ matrix.ckan-version }}.bash

      - name: Initialize DB
        run: ./bin/init-db.bash

      - name: Run tests
        run: |
          pytest \
            --ckan-ini=test.ini \
            --cov=ckanext.unhcr \
            --cov-report=xml \
            --cov-append \
            --disable-warnings \
            ckanext/unhcr/tests/pt

      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
